### ISSUE TITLE
[8.0] Migração l10n_br_stock

### ISSUE THREAD

**Issue by danimaribeiro** [odoo-brazil/l10n-brazil#11]
Migração l10n_br_stock em andamento

**Comment by renatonlima** [comment]
Olá @danimaribeiro, @mileo 


Eu dei uma olhada na migração do estoque na branch 8.0 https://github.com/odoo-brazil/l10n-brazil e vi que foi feito algumas desenvolvimentos, mas agora na versão 8.0 o módulo estoque foi dividido em stock a stock_account, para permitir que se instale o modulo de estoque sem a necessidade de instalar a contabilidade (account), para manter esta modularidade nós fizemos esta divisão em l10n_br_stock e l10n_br_stock_account na branch https://github.com/akretion/l10n-brazil/tree/migration/l10n_br_stock por favor verifique esta branch e me fale o que pode ser integrado, você pode propor um PR nesta branch, assim podemos integrar todas as contribuições
