### ISSUE TITLE
[8.0] Migração l10n_br_zip

### ISSUE THREAD

**Issue by danimaribeiro** [odoo-brazil/l10n-brazil#12]
MIgração do módulo l10n_br_zip

**Comment by renatonlima** [comment]
Olá @danimaribeiro 

Eu vi que ainda não tem nenhum push relacionada a esta tarefa na branch 8.0, caso você tenha alguma contribuição, sugiro você fazer um PR na branch https://github.com/akretion/l10n-brazil/tree/migration/l10n_br_zip, pois fizemos um PR desta feature branch https://github.com/OCA/l10n-brazil/pull/150 para subir o que fizemos e neste caso podemos unir as contribuições.

**Comment by danimaribeiro** [comment]
Não foi migrado este módulo ainda. Vou fechar este issue.
