### ISSUE TITLE
Frete, Seguro e Outros Custos do Pedido de Venda não são copiados para a Fatura

### ISSUE THREAD

**Issue by mstuttgart** [odoo-brazil/l10n-brazil#132]
Quando criamos um Pedido de Venda e no campo **"Criar Nota Fiscal"** escolhemos a opção **"Pedido na Entrega"**, o valor do frete inserido no Pedido de Venda não é tranferido para a fatura.

![frete1](https://cloud.githubusercontent.com/assets/8174740/11318967/4f5908d4-904e-11e5-935e-3f06230fe9d1.png)

Porém, quando no campo **"Criar Nota Fiscal"**, escolhemos a opção **"Sob Demanda"**, o valor do frete é tranferido normalmente para a fatura.

Passos para reproduzir o erro:
* Localização da Odoo-Brazil, *branch* 8.0 atualizada.
Ultimo commit: https://github.com/odoo-brazil/l10n-brazil/commit/32fc2e0a4955a358f9bcb30646bc56d04cf8e31b
* Base nova com dados de demonstração instalados;
* Módulos instalados: **sale, l10n_br_zip_correios, l10n_br_delivery**;
* Usuário Admin com permissão de **"Procedimentos técnicos"** e em Vendas como **"gerente"**;
* Criar Pedido de Venda com cliente **"Akretion São Paulo"** e na linha do Pedido, adicionar o produto "**Mouse Óptico**";
* **[IMPORTANTE]** No campo **"Criar Nota Fiscal"** escolhemos a opção **"Pedido na Entrega"**
* Clicar na opção **"atualizar"** para que o valor do pedido seja atualizado;
* Adicionar um valor qualquer de frete e clicar novamente na opção **"atualizar**" para que o frete seja contabilizado;
* Confirmar Pedido de Venda e clicar no botão **"Ver Ordem de Entrega"**.  Realizar o procedimeto de entrega: **"Forçar Disponibilidade->Transferir->Aplicar->Criar Fatura->Criar"**
* Na fatura recém-criada, na aba **"Dados Adicionais->Transporte"** o valor do frete permanece zerado. Consequentemente, quando transmitimos a fatura, o valor do Frete no XML e no DANFE permanecem zerados.

![frete2](https://cloud.githubusercontent.com/assets/8174740/11318970/5800cbf2-904e-11e5-9462-f1bce32830cf.png)

Vi que o valor dos fretes na linha da fatura são somados e depois copiados ao campo de frete mostrado acima. [Aqui](https://github.com/odoo-brazil/l10n-brazil/blob/8.0/l10n_br_account_product/account_invoice.py#L62)
Porém o valor do frete já vem zerado na linha da fatura. Tentei rastrear onde os valores eram transferidos para a mesma (usando a opção **"Pedido na Entrega"**), mas ainda não obtive sucesso.

Além do frete, transportadora, tipo do frete, valor seguro e valor outros custos também não são carregados do Pedido de Venda e/ou Ordem de Entrega.

**Comment by mileo** [comment]
Esta passando aqui? https://github.com/odoo-brazil/l10n-brazil/blob/8.0/l10n_br_delivery/stock.py#L45

**Comment by mstuttgart** [comment]
Não. Está passando apenas no método acima: https://github.com/odoo-brazil/l10n-brazil/blob/8.0/l10n_br_delivery/stock.py#L34
