### ISSUE TITLE
Data da Fatura na tree view vazia e na form com valor

### ISSUE THREAD

**Issue by mstuttgart** [odoo-brazil/l10n-brazil#133]
Coluna **"Data da Fatura"** na *tree view* não armazena o valor do campo **"Data Emissão"** exibida na *form view*, quando a fatura esta como **provisória**. 

*tree view*
![datafatura](https://cloud.githubusercontent.com/assets/8174740/11325119/aa04503e-912c-11e5-82f4-5b96ae646e0d.png)

*form view*
![datafatura1](https://cloud.githubusercontent.com/assets/8174740/11325120/afa9b376-912c-11e5-8b96-3dfcab3e7125.png)

As duas deveriam mostrar a mesma data, uma vez que representam o mesmo dado (data da fatura).

**Comment by mileo** [comment]
Verifique se o campo invoice_date esta sendo preenchido.

Existem 2 campos invoice_date_hour e o invoice_date.

Para manter a compatibilidade com o core o invoice_date tem que ser preenchido no action_move_create ou no action_assign ou até no compute do payment_term

**Comment by mstuttgart** [comment]
O campo **invoice_date** é preenchido com o valor da data contida em *invoice_date_hour* apenas após confirmamos a fatura. 

No estado provisório, os valores dos dois campos não são sincronizados.
