### ISSUE TITLE
Erro ao carregar impostos cadastrados na empresa na Fatura

### ISSUE THREAD

**Issue by pauloneda** [odoo-brazil/l10n-brazil#153]
Ao criar um pedido de venda, as linhas do pedido carregam corretamente os impostos.
Ao Gerar a fatura os impostos aparecem na linha, porém as CSTS não são carregadas.

![produto](https://cloud.githubusercontent.com/assets/7142325/15502710/1042b864-218c-11e6-9a67-349038bd31f4.jpg)
![icms](https://cloud.githubusercontent.com/assets/7142325/15502714/17b40d28-218c-11e6-899a-bf33dd226d50.jpg)

**Comment by mileo** [comment]
Como esta seu cadastro da empresa, tira uma foto tb.

**Comment by pauloneda** [comment]
@mileo 
Segue cadastro da Empresa.
![impostos_empresa](https://cloud.githubusercontent.com/assets/7142325/15546421/37b1254e-2276-11e6-8588-fac95865365b.jpg)

**Comment by pauloneda** [comment]
@mileo 
Pode fechar, mudei o ICMS no cadastro da empresa e utilizei o mapeamento nas Posições Fiscais corretamente.
