### ISSUE TITLE
Dúvida sobre CFOPs de consignação x917, ordens de pagamento e livro contábil para receitas 

### ISSUE THREAD

**Issue by jorgesallum** [odoo-brazil/l10n-brazil#157]
Caros, talvez esta pergunta esteja fora do escopo, mas ouso perguntar aqui na busca de alguma ajuda. 

Não há processo contábil associado a CFOPs?  Por exemplo, Ordens de Venda (SOs) associadas à CFOP x917, são consideradas como venda regular e abrem-se ordens de pagamento. Há algum projeto para criar processos contábeis segundo as CFOPs?

Obrigado, Jorge Sallum

**Comment by danimaribeiro** [comment]
Não existe nenhum cálculo em cima da CFOP.
A CFOP é apenas informativo, você tem que vincular a CFOP correta conforme suas categorias e posições fiscais.

**Comment by jorgesallum** [comment]
Muito obrigado!
