### ISSUE TITLE
Campo CNPJ não permite cadastrar fornecedor estrangeiro

### ISSUE THREAD

**Issue by leticiadnsouza** [odoo-brazil/l10n-brazil#19]
Não é possível salvar fornecedores de outro país com seu próprio número de registro pois a validação do campo CNPJ impede que um número em outro formato (para identificação do fornecedor) seja inserido.

**Comment by ATSTI** [comment]
Como estou usando a localização, não sei se seria possível usar o campo do CNPJ, pra outra numeração para pessoa juridica. 

Por outro lado tanto ai como na Localização, a validação deste campo como CNPJ só deveria ocorrer se o PAIS for "Brasil".

**Comment by danimaribeiro** [comment]
@ATSTI O que você quer dizer com "usar o campo do CNPJ, pra outra numeração para pessoa juridica. "  ?

**Comment by crsilveira** [comment]
Estava respondendo a este post: Não é possível salvar fornecedores de outro país com seu próprio número de registro pois a validação do campo CNPJ impede que um número em outro formato (para identificação do fornecedor) seja inserido. 

Da Leticia,  mas exclui meu comentário ... Não tinha nada haver.

**Comment by renatonlima** [comment]
Atualmente na NFe 3.10 uma nota fiscal de exportação ou uma operação envolvendo um pessoa fisica estrangeira deve conter um Id Estrangeiro que é um campo equivalente ao CNPJ/CPF (Vat Number) ou o passaporte no caso de PF, Temos um cliente que emite NFe de exportação e modificamos a na localização para não fazer a validação de CNPJ/CPF caso o país do parceiro não seja o Brasil. https://github.com/akretion/l10n-brazil/blob/migration/l10n_br_base/l10n_br_base/models/res_partner.py#L147

**Comment by danimaribeiro** [comment]
Talvez seria legal utilizar estes módulos da OCA para o parceiro.
https://github.com/OCA/partner-contact/tree/8.0/passport
Como este do passaporte, e utilizar este registro como idEstrangeiro.
