### ISSUE TITLE
Desconto total na cotação está sendo desconsiderada

### ISSUE THREAD

**Issue by danimaribeiro** [odoo-brazil/l10n-brazil#22]
Passos:
Habilitar no cadastro de usuários o Desconto Total.
Criar uma nova cotação e digitar um percentual de desconto.
O mesmo não é levado em conta no cálculo

Ao tentar editar o percentual cadastrado também ocorre o erro dizendo que a Moeda é obrigatória, porém o campo moeda não está visível.

**Comment by mileo** [comment]
Tem que acertar o onchange e fazer como eu fiz no frete, inclusive o total do desconto não esta sendo somado
Em 19/05/2015 16:53, Danimar Ribeiro <notifications@github.com> escreveu:Passos:
Habilitar no cadastro de usuários o Desconto Total.
Criar uma nova cotação e digitar um percentual de desconto.
O mesmo não é levado em conta no cálculo

Ao tentar editar o percentual cadastrado também ocorre o erro dizendo que a Moeda é obrigatória, porém o campo moeda não está visível.
