### ISSUE TITLE
Impostos calculados de forma errada na cotação e pedido de venda

### ISSUE THREAD

**Issue by marceloeng** [odoo-brazil/l10n-brazil#26]
Impostos computados de forma errada na cotação e pedido de venda. Na fatura, são calculados de forma correta.

Está sendo adicionando o valor do imposto ao serviço. Ex: Se o valor do serviço for de 100,00 e o imposto for de 6%, o valor do pedido será de 106,00 da cotação e pedido de venda. Ao passar para fatura, o valor fica em 100,00.

**Comment by danimaribeiro** [comment]
Segue teste feito com um serviço. O calculo com ISSQN 3% calculou corretamente tanto no pedido quanto na fatura.
![cotacao de servico](https://cloud.githubusercontent.com/assets/854781/7997099/6ba2c15e-0afe-11e5-8f45-023ffdf1c951.PNG)

**Comment by marceloeng** [comment]
Danimar,

Na imagem apresentada, não mostra o valor do imposto. Seria isso mesmo?

**Comment by danimaribeiro** [comment]
Somente o IPI que aparece ali, o ICMS e outros impostos que já estão embutidos no valor não aparecem, mas são calculados corretamente.

**Comment by marceloeng** [comment]
Legal Danimar...Vou testar novamente e qualquer coisa, te aviso.

Abraço...

**Comment by danimaribeiro** [comment]
Alguma novidade em relação a este? 
Vou fechar o bug, qualquer problema eu reabro dai.

**Comment by marceloeng** [comment]
blz
