### ISSUE TITLE
Dúvida em cálculo em l10n_br_sale_product, método _amount_all

### ISSUE THREAD

**Issue by alexsandrohaag** [odoo-brazil/l10n-brazil#50]
Qual a finalidade na linha (50) abaixo para os cálculos de impostos do pedido/cotação?

```python
val -= (line.insurance_value + line.freight_value + line.other_costs_value)
```

Em princípio comentando esta linha os cálculos do pedido funcionaram.

Ex.:
Com a linha acima:
![calculo-errado](https://cloud.githubusercontent.com/assets/4663105/8977651/698963de-3671-11e5-9cdb-88c7b5698478.png)

Com  a linha comentada:
![calculo-ok2](https://cloud.githubusercontent.com/assets/4663105/8977657/76720934-3671-11e5-9f2f-788532764123.png)

**Comment by danimaribeiro** [comment]
No cadastro de empresa está configurado os seguintes impostos?

![capturar](https://cloud.githubusercontent.com/assets/854781/8989577/5c47dec4-36c3-11e5-91f4-e051e49fd5ba.PNG)

**Comment by hgsoft** [comment]
Não. Estes estão em branco.

**Comment by hgsoft** [comment]
Vou preencher e testar.

**Comment by danimaribeiro** [comment]
Modelo para preenchimento.
https://github.com/odoo-brazil/l10n-brazil/pull/30/files

**Comment by alexsandrohaag** [comment]
Sim, preenchendo ali funcionou certinho.
