### ISSUE TITLE
Erro ao abrir a Análise de Vendas

### ISSUE THREAD

**Issue by guilindner** [odoo-brazil/l10n-brazil#58]
Ao entrar em Relatórios -> Vendas -> Análise de Vendas, o seguinte erro ocorre:
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column sale_report.section_id does not exist
LINE 3: ...rm_case_section" as "sale_report__section_id" ON ("sale_repo...

Todas as outras análises abrem corretamente.

**Comment by danimaribeiro** [comment]
Corrigido aqui:
https://github.com/odoo-brazil/l10n-brazil/pull/38

**Comment by mileo** [comment]
Pode ser que vc precise dar drop na view e criar novamente.
