### ISSUE TITLE
Erro de tamanho do id do form :  l10n_br_account_product/product_view.xml

### ISSUE THREAD

**Issue by ATSTI** [odoo-brazil/l10n-brazil#68]
ERROR base_a openerp.tools.convert: id: l10n_br_account_product_fiscal_classification_product_normal_form_view is to long (max: 64)

**Comment by danimaribeiro** [comment]
Consegue postar a mensagem completa de erro?

**Comment by ATSTI** [comment]
Danimar só havia esta linha de erro , vc viu o final dela ? 

   is to long (max: 64)

**Comment by danimaribeiro** [comment]
Esse erro sempre acontece nos builds:
https://travis-ci.org/odoo-brazil/odoo-brazil-eletronic-documents/jobs/77716677

Mas eu nunca peguei ele ao executar o odoo.

**Comment by ATSTI** [comment]
Eu estava dando um update=all .

**Comment by mileo** [comment]
Ele ocorre no Odoo também. O id esta muito longo, provável que de problema ao referenciar essa view em alguma herança.

Vale a pena reduzir. @ATSTI vc pode corrigir?

**Comment by danimaribeiro** [comment]
Acho que corrigiram no 8.0:
https://github.com/odoo/odoo/pull/8142

**Comment by mileo** [comment]
Boa!
