### ISSUE TITLE
[8.0] Campo cnpj/cpf não esta lançando o onchange.

### ISSUE THREAD

**Issue by danimaribeiro** [odoo-brazil/l10n-brazil#7]
Campo está ficando sem o atributo que diz ao campo para disparar o onchange.
Talvez seja bug na nova api.

**Comment by danimaribeiro** [comment]
Correção:
Necessita converter este onchange --> 
https://github.com/odoo-brazil/l10n-brazil/blob/8.0/l10n_br_account/res_partner.py#L378

**Comment by sadamo** [comment]
@mstuttgart
