### ISSUE TITLE
Erro: NotImplementedError: 'update' not supported on frozendict

### ISSUE THREAD

**Issue by ATSTI** [odoo-brazil/l10n-brazil#76]
File "..addons/account_fiscal_position_rule_sale/sale.py", line 55, in onchange_partner_id
    return self._fiscal_position_map(result, **kwargs)
  File "../openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "..addons/l10n_br_sale/sale.py", line 207, in _fiscal_position_map
    context.update({'use_domain': ('use_sale', '=', True)})
  File "..openerp/tools/misc.py", line 1272, in update
    raise NotImplementedError("'update' not supported on frozendict")
NotImplementedError: 'update' not supported on frozendict

@api.model                                                                                                                                            
 def _fiscal_position_map(self, result, context=None, **kwargs):

Resolvido assim: 

   context=dict(context)    
  seguindo esta dica:    http://poncesoft.blogspot.com.br/2015/03/solucion-error-notimplementederror.html

**Comment by danimaribeiro** [comment]
Já foi corrigido nas últimas modificações que fiz referente aos testes unitários:

https://github.com/odoo-brazil/l10n-brazil/blob/8.0/l10n_br_sale/sale.py#L202
https://github.com/odoo-brazil/l10n-brazil/commit/e700c4d2eb9f52b0afbc067808555258f100d12b#diff-e524c77c5d25226e3a751272c206a52d
