### ISSUE TITLE
[8.0] Problema ao criar novo cliente - onchange zip

### ISSUE THREAD

**Issue by danimaribeiro** [odoo-brazil/l10n-brazil#8]
Logo ao clicar em Criar cliente o erro acontece.
Erro: "onchange_mask_zip takes 1 argument (5 given)".

**Comment by mileo** [comment]
@danimaribeiro consegue especificar a linha do erro / copiar o log?

**Comment by danimaribeiro** [comment]
@mileo Eu já corrigi, ja vou enviar o PR.
